Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd     = os.path.join(str(Dir('#')), 'one_wire_drivers/')
src	= Glob('*.c')
CPPPATH = [cwd]

group = DefineGroup('DS28E80', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
